/**
 * Isometric drawing primitives.
 *
 * Pure functions that turn grid-space numbers into SVG path data. No Angular,
 * no component state — so they can be unit-tested and reused by any tile art.
 *
 * Conventions used throughout:
 *   (bx, by)  base centre of a solid, on the ground plane
 *   w         half-width in tile units (1 = a full tile)
 *   h         height as a pure vertical offset
 *   t         height up a wall at which a feature sits
 *   f         fraction (0..1) along an edge
 */

import { Pt, Seg, FenceSide, TILE_W, TILE_H } from './iso.model';

const HW = TILE_W / 2;
const HH = TILE_H / 2;

// ---------------------------------------------------------------- ground ---

/** The full tile diamond centred at (x, y). */
export function diamond(x: number, y: number): string {
  return `M${x},${y - HH} L${x + HW},${y} L${x},${y + HH} L${x - HW},${y} Z`;
}

/** A smaller diamond inset by k (0..1) — pools, patios, paving, plazas. */
export function diamondAt(x: number, y: number, k: number): string {
  const hw = HW * k;
  const hh = HH * k;
  return `M${x},${y - hh} L${x + hw},${y} L${x},${y + hh} L${x - hw},${y} Z`;
}

// ------------------------------------------------------------------ box ----
// Every solid is three polygons: a top diamond, a lit right face and a shaded
// left face. One hue per material, three values.

/** Top face, raised h above the base point. */
export function boxTop(bx: number, by: number, w: number, h: number): string {
  const hw = HW * w;
  const hh = HH * w;
  const y = by - h;
  return `M${bx},${y - hh} L${bx + hw},${y} L${bx},${y + hh} L${bx - hw},${y} Z`;
}

/** Left (-x) vertical face — the shaded side. */
export function boxLeft(bx: number, by: number, w: number, h: number): string {
  const hw = HW * w;
  const hh = HH * w;
  return `M${bx - hw},${by - h} L${bx},${by - h + hh} L${bx},${by + hh} L${bx - hw},${by} Z`;
}

/** Right (+x) vertical face — the lit side. */
export function boxRight(bx: number, by: number, w: number, h: number): string {
  const hw = HW * w;
  const hh = HH * w;
  return `M${bx},${by - h + hh} L${bx + hw},${by - h} L${bx + hw},${by} L${bx},${by + hh} Z`;
}

// -------------------------------------------------------------- glazing ----

/** A continuous window band across the left face. */
export function windowLeft(bx: number, by: number, w: number, h: number, t: number): string {
  const hw = HW * w * 0.72;
  const hh = HH * w * 0.72;
  const yTop = by - h + t;
  const band = 7;
  return `M${bx - hw},${yTop} L${bx},${yTop + hh} L${bx},${yTop + hh + band} L${bx - hw},${yTop + band} Z`;
}

/** A continuous window band across the right face. */
export function windowRight(bx: number, by: number, w: number, h: number, t: number): string {
  const hw = HW * w * 0.72;
  const hh = HH * w * 0.72;
  const yTop = by - h + t;
  const band = 7;
  return `M${bx},${yTop + hh} L${bx + hw},${yTop} L${bx + hw},${yTop + band} L${bx},${yTop + hh + band} Z`;
}

/** One discrete pane on the left face, at fraction f along it.
 *  Separate openings read as real windows; one long strip does not. */
export function paneLeft(
  bx: number, by: number, w: number, h: number, t: number, f: number, pw = 0.2,
): string {
  const hw = HW * w;
  const hh = HH * w;
  const x0 = bx - hw + hw * f;
  const y0 = by - h + t + hh * f;
  const x1 = bx - hw + hw * (f + pw);
  const y1 = by - h + t + hh * (f + pw);
  const band = 8;
  return `M${x0},${y0} L${x1},${y1} L${x1},${y1 + band} L${x0},${y0 + band} Z`;
}

/** One discrete pane on the right face, at fraction f along it. */
export function paneRight(
  bx: number, by: number, w: number, h: number, t: number, f: number, pw = 0.2,
): string {
  const hw = HW * w;
  const hh = HH * w;
  const x0 = bx + hw * f;
  const y0 = by - h + t + hh * (1 - f);
  const x1 = bx + hw * (f + pw);
  const y1 = by - h + t + hh * (1 - f - pw);
  const band = 8;
  return `M${x0},${y0} L${x1},${y1} L${x1},${y1 + band} L${x0},${y0 + band} Z`;
}

/** Two openings set toward the ends of a villa wall. */
export const PANE_SPOTS = [0.14, 0.62];
/** Evenly spaced openings across a town-hall wall. */
export const HALL_WIN_SPOTS = [0.10, 0.34, 0.58, 0.80];

// ---------------------------------------------------------------- fence ----
// Posts and rails are generated by stepping a constant fraction along an edge
// pair, never hand-placed.

/** The two corners a fence run spans, for the given side. */
function fenceEdges(x: number, y: number, side: FenceSide, inset: number): [Pt, Pt, Pt] {
  const hw = HW * inset;
  const hh = HH * inset;
  const near: Pt = side === 'front' ? { x, y: y + hh } : { x, y: y - hh };
  return [{ x: x - hw, y }, near, { x: x + hw, y }];
}

/** Horizontal rails threaded between the posts of one side, at each height. */
export function fenceRailPath(
  x: number, y: number, side: FenceSide, inset = 0.92, heights: number[] = [6, 12],
): string {
  const hw = HW * inset;
  const hh = HH * inset;
  const nearY = side === 'front' ? y + hh : y - hh;
  return heights
    .map((h) => `M${x - hw},${y - h} L${x},${nearY - h} L${x + hw},${y - h}`)
    .join(' ');
}

/** Evenly stepped post positions along one side. */
export function fencePostBoxes(
  x: number, y: number, side: FenceSide, inset = 0.92, n = 4,
): Pt[] {
  const [left, near, right] = fenceEdges(x, y, side, inset);
  const out: Pt[] = [];
  for (const [a, b] of [[left, near], [near, right]] as const) {
    for (let i = 0; i <= n; i++) {
      // skip the shared corner on the second run so posts aren't doubled
      if (b === right && i === 0) continue;
      const f = i / n;
      out.push({ x: a.x + (b.x - a.x) * f, y: a.y + (b.y - a.y) * f });
    }
  }
  return out;
}

/** Rails along the two edges of one side, as a stroked path. */
export function sideRails(x: number, y: number, side: FenceSide, inset = 0.9, t = 9): string {
  const hw = HW * inset;
  const hh = HH * inset;
  const nearY = side === 'front' ? y + hh : y - hh;
  const rail = (dy: number) => `M${x - hw},${y - dy} L${x},${nearY - dy} L${x + hw},${y - dy}`;
  return `${rail(2)} ${rail(2 + t)}`;
}

/** Thin vertical posts along the two edges of one side. */
export function sidePosts(x: number, y: number, side: FenceSide, inset = 0.9, t = 11): Seg[] {
  const [left, near, right] = fenceEdges(x, y, side, inset);
  const out: Seg[] = [];
  for (const [a, b] of [[left, near], [near, right]] as const) {
    for (const f of [0, 0.5, 1]) {
      const px = a.x + (b.x - a.x) * f;
      const py = a.y + (b.y - a.y) * f;
      out.push({ x1: px, y1: py - 2, x2: px, y2: py - 2 - t });
    }
  }
  return out;
}

// ------------------------------------------------------- site structures ---

/** Four corner columns of an open construction frame. */
export function frameColumns(x: number, y: number, w: number): Pt[] {
  const hw = HW * w;
  const hh = HH * w;
  return [
    { x: x - hw, y },
    { x, y: y - hh },
    { x: x + hw, y },
    { x, y: y + hh },
  ];
}

/** A horizontal ring tying the frame columns at a given height. */
export function frameRing(x: number, y: number, w: number, h: number): string {
  const hw = HW * w;
  const hh = HH * w;
  return `M${x - hw},${y - h} L${x},${y - hh - h} L${x + hw},${y - h} L${x},${y + hh - h} Z`;
}

// ------------------------------------------------------------- planting ----

/** Trimmed hedge cubes flanking a villa's entrance. */
export function villaBushes(x: number, y: number): Pt[] {
  return [
    { x: x + 34, y: y + 14 },
    { x: x + 14, y: y + 24 },
  ];
}
